language: php
dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpspec run --format=dot