version: "2"

services:

  php:
    build: docker/php
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - USE_XDEBUG=yes
    links:
      - memcached

  memcached:
    image: memcached:latest